services:
  - type: web
    name: api-clinica
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-api
          property: connectionString

databases:
  - name: postgres-api
    databaseName: clinica_db
    user: clinica_user
