services:
  - type: web
    name: fastapi-api
    runtime: docker
    region: oregon  # Puedes cambiar la región
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api-db
          property: connectionString
    dockerContext: .
    dockerfilePath: ./Dockerfile

databases:
  - name: api-db
    region: oregon
    plan: free
